# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkls-VqEGvZvc2L1WKoGpw5jiM8nR178
"""

x = [int(i) for i in input("Enter the values:").split()]
print(x)
print(sum(x))