# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-nXWTyr6VHJ-AtqvxTS7f9sBnZpOFRU
"""

s = input('Enter the lottery word: ').lower()

freq = [0] * 26

# lowercase alphabets - ASCII code: 97 to 122
for i in s:
  freq[ord(i) - 97] += 1

print(freq)
x = freq.index(max(freq))
print(x)
print("Lottery Letter:",chr(97 + x))