# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3hfQmdcW7yNkStd5KtaGIb0XMlEoKOE
"""

Tv = {'Apple':100, 'Power':1292, 'Topup' : 88}
 
Keymax = max(Tv, key= lambda x: Tv[x])
print(Keymax)