# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1omRFKhDpmBG2faTcQJBxSC5su9HTfJDA
"""

def fun(n):

  return n % 3 == 0 and n % 5 == 0
  
li = list(range(1, 201)) 

print(list(filter(fun, li)))