# -*- coding: utf-8 -*-
"""Day7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-IWD5-K8pVcL2EWLPQhrrxSq3J7GsFr
"""

import mysql.connector as sql           # importing module

# Connecting the local mysql database
database = sql.connect(host = 'localhost', user = 'root', passwd = 'getit1298', database = 'demodata')

data_base = database.cursor()


data_base.execute("update student set Maths_marks = 90 where Roll_no = 351")     # Update the record 
data_base.execute("select * from student")        # View the table

for i in data_base:
    print(i)

data_base.close()
database.commit()       # commit changes or save changes.